"""

Revision ID: 907ad47e5d50
Revises: 4a4246d6afa2
Create Date: 2018-10-27 15:44:33.964301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907ad47e5d50'
down_revision = '4a4246d6afa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('session_user_id_key', 'session', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('session_user_id_key', 'session', ['user_id'])
    # ### end Alembic commands ###
