"""

Revision ID: 9e9d7947342c
Revises: 7e469ff1b33c
Create Date: 2018-10-27 15:21:58.977013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9d7947342c'
down_revision = '7e469ff1b33c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
