"""

Revision ID: c50be0595f84
Revises: eb3d8aee6c12
Create Date: 2018-10-27 16:11:52.377321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c50be0595f84'
down_revision = 'eb3d8aee6c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'session_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
