"""

Revision ID: 9ad1f44b378a
Revises: 907ad47e5d50
Create Date: 2018-10-27 15:46:26.963331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad1f44b378a'
down_revision = '907ad47e5d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'session', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='unique')
    # ### end Alembic commands ###
