"""

Revision ID: ef6445ab569a
Revises: b4463dfd8c77
Create Date: 2018-09-23 12:06:50.015163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6445ab569a'
down_revision = 'b4463dfd8c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('timeout', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    # op.create_unique_constraint('unique_friendships', 'friends', ['first_user', 'second_user'])
    op.add_column('user', sa.Column('token_id', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token_id')
    # op.drop_constraint('unique_friendships', 'friends', type_='unique')
    op.drop_table('session')
    # ### end Alembic commands ###
