"""

Revision ID: 7e469ff1b33c
Revises: dd4d24f548ef
Create Date: 2018-10-27 14:16:44.460390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e469ff1b33c'
down_revision = 'dd4d24f548ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'session', 'user', ['user_id'], ['id'])
    op.drop_constraint('user_session_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'session_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_session_id_fkey', 'user', 'session', ['session_id'], ['id'])
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_column('session', 'user_id')
    # ### end Alembic commands ###
