"""

Revision ID: eb3d8aee6c12
Revises: 9ad1f44b378a
Create Date: 2018-10-27 15:55:29.455068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb3d8aee6c12'
down_revision = '9ad1f44b378a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
