"""

Revision ID: 716df107576f
Revises: c50be0595f84
Create Date: 2018-10-27 16:17:40.756402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716df107576f'
down_revision = 'c50be0595f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
