"""

Revision ID: cb2f91aa89d7
Revises: b4463dfd8c77
Create Date: 2018-10-20 12:51:51.216351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb2f91aa89d7'
down_revision = 'b4463dfd8c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('expire', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('friends')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('first_user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('second_user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['first_user'], ['user.id'], name='friends_first_user_fkey'),
    sa.ForeignKeyConstraint(['second_user'], ['user.id'], name='friends_second_user_fkey'),
    sa.PrimaryKeyConstraint('first_user', 'second_user', name='unique_friendships')
    )
    op.drop_table('session')
    # ### end Alembic commands ###
