"""

Revision ID: dd4d24f548ef
Revises: cb2f91aa89d7
Create Date: 2018-10-27 14:12:42.452845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4d24f548ef'
down_revision = 'cb2f91aa89d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'user_id')
    op.add_column('user', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'session', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'session_id')
    op.add_column('session', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
