debug: &debug false
host: localhost

api:
    host: localhost
    port: 8000

redis:
    host: localhost
    port: 6379
    db:
        cache: 0

db:
    master:
        dsn: postgresql://postgres:postgres@localhost/postgres
        pool_size: 23
        max_overflow: 2

logging:
    LoggerToFile:
        level: WARNING
        filename: src/log/errors.log
        maxBytes: 1024
        backupCount: 3
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
